//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irmac.MailingCycle.BLLServiceLoader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/CommonService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_localhost_CommonService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_localhost_CommonService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/OrderService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_OrderService_OrderService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_OrderService_OrderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/AccaService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Acca_AccaService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Acca_AccaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/CommonService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Common_CommonService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Common_CommonService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/DesignService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Design_DesignService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Design_DesignService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/FarmService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Farm_FarmService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Farm_FarmService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/MessageService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Message_MessageService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Message_MessageService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/OrderService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Order_OrderService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Order_OrderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/ProductService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Product_ProductService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Product_ProductService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/RegistrationService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Registration_RegistrationService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Registration_RegistrationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/ScheduleService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_Schedule_ScheduleService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_Schedule_ScheduleService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1073/ShoppingCartService.asmx")]
        public string Irmac_MailingCycle_BLLServiceLoader_ShoppingCart_ShoppingCartService {
            get {
                return ((string)(this["Irmac_MailingCycle_BLLServiceLoader_ShoppingCart_ShoppingCartService"]));
            }
        }
    }
}
