//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Irmac.MailingCycle.BLLServiceLoader.Common {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonServiceSoap", Namespace="http://mc.mkbedev.com/BLLService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryInfo[]))]
    public partial class CommonService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCountriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLookupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLookupDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPropertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPropertyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CommonService() {
            this.Url = "http://mc1.mkbedev.com/BLLService/CommonService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCountriesCompletedEventHandler GetCountriesCompleted;
        
        /// <remarks/>
        public event GetStatesCompletedEventHandler GetStatesCompleted;
        
        /// <remarks/>
        public event GetLookupsCompletedEventHandler GetLookupsCompleted;
        
        /// <remarks/>
        public event GetLookupDetailsCompletedEventHandler GetLookupDetailsCompleted;
        
        /// <remarks/>
        public event GetPropertyCompletedEventHandler GetPropertyCompleted;
        
        /// <remarks/>
        public event GetAgentsListCompletedEventHandler GetAgentsListCompleted;
        
        /// <remarks/>
        public event GetUsersByRoleCompletedEventHandler GetUsersByRoleCompleted;
        
        /// <remarks/>
        public event InsertPropertyCompletedEventHandler InsertPropertyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetCountries", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CountryInfo[] GetCountries() {
            object[] results = this.Invoke("GetCountries", new object[0]);
            return ((CountryInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCountriesAsync() {
            this.GetCountriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCountriesAsync(object userState) {
            if ((this.GetCountriesOperationCompleted == null)) {
                this.GetCountriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountriesOperationCompleted);
            }
            this.InvokeAsync("GetCountries", new object[0], this.GetCountriesOperationCompleted, userState);
        }
        
        private void OnGetCountriesOperationCompleted(object arg) {
            if ((this.GetCountriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetStates", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StateInfo[] GetStates(int countryId) {
            object[] results = this.Invoke("GetStates", new object[] {
                        countryId});
            return ((StateInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStatesAsync(int countryId) {
            this.GetStatesAsync(countryId, null);
        }
        
        /// <remarks/>
        public void GetStatesAsync(int countryId, object userState) {
            if ((this.GetStatesOperationCompleted == null)) {
                this.GetStatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatesOperationCompleted);
            }
            this.InvokeAsync("GetStates", new object[] {
                        countryId}, this.GetStatesOperationCompleted, userState);
        }
        
        private void OnGetStatesOperationCompleted(object arg) {
            if ((this.GetStatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatesCompleted(this, new GetStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetLookups", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LookupInfo[] GetLookups(string category) {
            object[] results = this.Invoke("GetLookups", new object[] {
                        category});
            return ((LookupInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLookupsAsync(string category) {
            this.GetLookupsAsync(category, null);
        }
        
        /// <remarks/>
        public void GetLookupsAsync(string category, object userState) {
            if ((this.GetLookupsOperationCompleted == null)) {
                this.GetLookupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLookupsOperationCompleted);
            }
            this.InvokeAsync("GetLookups", new object[] {
                        category}, this.GetLookupsOperationCompleted, userState);
        }
        
        private void OnGetLookupsOperationCompleted(object arg) {
            if ((this.GetLookupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLookupsCompleted(this, new GetLookupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetLookupDetails", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LookupInfo GetLookupDetails(int lookupId) {
            object[] results = this.Invoke("GetLookupDetails", new object[] {
                        lookupId});
            return ((LookupInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetLookupDetailsAsync(int lookupId) {
            this.GetLookupDetailsAsync(lookupId, null);
        }
        
        /// <remarks/>
        public void GetLookupDetailsAsync(int lookupId, object userState) {
            if ((this.GetLookupDetailsOperationCompleted == null)) {
                this.GetLookupDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLookupDetailsOperationCompleted);
            }
            this.InvokeAsync("GetLookupDetails", new object[] {
                        lookupId}, this.GetLookupDetailsOperationCompleted, userState);
        }
        
        private void OnGetLookupDetailsOperationCompleted(object arg) {
            if ((this.GetLookupDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLookupDetailsCompleted(this, new GetLookupDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetProperty", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PropertyInfo GetProperty(string name) {
            object[] results = this.Invoke("GetProperty", new object[] {
                        name});
            return ((PropertyInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetPropertyAsync(string name) {
            this.GetPropertyAsync(name, null);
        }
        
        /// <remarks/>
        public void GetPropertyAsync(string name, object userState) {
            if ((this.GetPropertyOperationCompleted == null)) {
                this.GetPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPropertyOperationCompleted);
            }
            this.InvokeAsync("GetProperty", new object[] {
                        name}, this.GetPropertyOperationCompleted, userState);
        }
        
        private void OnGetPropertyOperationCompleted(object arg) {
            if ((this.GetPropertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPropertyCompleted(this, new GetPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetAgentsList", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RegistrationInfo[] GetAgentsList() {
            object[] results = this.Invoke("GetAgentsList", new object[0]);
            return ((RegistrationInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentsListAsync() {
            this.GetAgentsListAsync(null);
        }
        
        /// <remarks/>
        public void GetAgentsListAsync(object userState) {
            if ((this.GetAgentsListOperationCompleted == null)) {
                this.GetAgentsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentsListOperationCompleted);
            }
            this.InvokeAsync("GetAgentsList", new object[0], this.GetAgentsListOperationCompleted, userState);
        }
        
        private void OnGetAgentsListOperationCompleted(object arg) {
            if ((this.GetAgentsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentsListCompleted(this, new GetAgentsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetUsersByRole", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RegistrationInfo[] GetUsersByRole(string roles) {
            object[] results = this.Invoke("GetUsersByRole", new object[] {
                        roles});
            return ((RegistrationInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByRoleAsync(string roles) {
            this.GetUsersByRoleAsync(roles, null);
        }
        
        /// <remarks/>
        public void GetUsersByRoleAsync(string roles, object userState) {
            if ((this.GetUsersByRoleOperationCompleted == null)) {
                this.GetUsersByRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByRoleOperationCompleted);
            }
            this.InvokeAsync("GetUsersByRole", new object[] {
                        roles}, this.GetUsersByRoleOperationCompleted, userState);
        }
        
        private void OnGetUsersByRoleOperationCompleted(object arg) {
            if ((this.GetUsersByRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByRoleCompleted(this, new GetUsersByRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/InsertProperty", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertProperty(string name, string value) {
            object[] results = this.Invoke("InsertProperty", new object[] {
                        name,
                        value});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPropertyAsync(string name, string value) {
            this.InsertPropertyAsync(name, value, null);
        }
        
        /// <remarks/>
        public void InsertPropertyAsync(string name, string value, object userState) {
            if ((this.InsertPropertyOperationCompleted == null)) {
                this.InsertPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPropertyOperationCompleted);
            }
            this.InvokeAsync("InsertProperty", new object[] {
                        name,
                        value}, this.InsertPropertyOperationCompleted, userState);
        }
        
        private void OnInsertPropertyOperationCompleted(object arg) {
            if ((this.InsertPropertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPropertyCompleted(this, new InsertPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class CountryInfo : BaseInfo {
        
        private int countryIdField;
        
        private string nameField;
        
        private bool isDefaultField;
        
        /// <remarks/>
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LookupInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public abstract partial class BaseInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class CreditCardInfo : BaseInfo {
        
        private LookupInfo typeField;
        
        private string numberField;
        
        private string cvvNumberField;
        
        private string holderNameField;
        
        private int expirationMonthField;
        
        private int expirationYearField;
        
        private AddressInfo addressField;
        
        /// <remarks/>
        public LookupInfo Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string CvvNumber {
            get {
                return this.cvvNumberField;
            }
            set {
                this.cvvNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HolderName {
            get {
                return this.holderNameField;
            }
            set {
                this.holderNameField = value;
            }
        }
        
        /// <remarks/>
        public int ExpirationMonth {
            get {
                return this.expirationMonthField;
            }
            set {
                this.expirationMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ExpirationYear {
            get {
                return this.expirationYearField;
            }
            set {
                this.expirationYearField = value;
            }
        }
        
        /// <remarks/>
        public AddressInfo Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class LookupInfo : BaseInfo {
        
        private int lookupIdField;
        
        private string nameField;
        
        /// <remarks/>
        public int LookupId {
            get {
                return this.lookupIdField;
            }
            set {
                this.lookupIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class AddressInfo : BaseInfo {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private CountryInfo countryField;
        
        private StateInfo stateField;
        
        private string zipField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string faxField;
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public CountryInfo Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public StateInfo State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class StateInfo : BaseInfo {
        
        private int stateIdField;
        
        private string nameField;
        
        /// <remarks/>
        public int StateId {
            get {
                return this.stateIdField;
            }
            set {
                this.stateIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class RegistrationInfo : BaseInfo {
        
        private int userIdField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string emailField;
        
        private string passwordQuestionField;
        
        private string passwordAnswerField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string companyNameField;
        
        private AddressInfo addressField;
        
        private CreditCardInfo creditCardField;
        
        private RegistrationStatus statusField;
        
        private System.DateTime signupDateField;
        
        private UserRole roleField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordQuestion {
            get {
                return this.passwordQuestionField;
            }
            set {
                this.passwordQuestionField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordAnswer {
            get {
                return this.passwordAnswerField;
            }
            set {
                this.passwordAnswerField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public AddressInfo Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardInfo CreditCard {
            get {
                return this.creditCardField;
            }
            set {
                this.creditCardField = value;
            }
        }
        
        /// <remarks/>
        public RegistrationStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SignupDate {
            get {
                return this.signupDateField;
            }
            set {
                this.signupDateField = value;
            }
        }
        
        /// <remarks/>
        public UserRole Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public enum RegistrationStatus {
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        ApprovalRequired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public enum UserRole {
        
        /// <remarks/>
        Agent,
        
        /// <remarks/>
        Printer,
        
        /// <remarks/>
        CSR,
        
        /// <remarks/>
        Admin,
        
        /// <remarks/>
        NullValue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class PropertyInfo : BaseInfo {
        
        private string nameField;
        
        private object valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCountriesCompletedEventHandler(object sender, GetCountriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CountryInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CountryInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetStatesCompletedEventHandler(object sender, GetStatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StateInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StateInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLookupsCompletedEventHandler(object sender, GetLookupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLookupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLookupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LookupInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LookupInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLookupDetailsCompletedEventHandler(object sender, GetLookupDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLookupDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLookupDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LookupInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LookupInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPropertyCompletedEventHandler(object sender, GetPropertyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PropertyInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PropertyInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAgentsListCompletedEventHandler(object sender, GetAgentsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegistrationInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegistrationInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUsersByRoleCompletedEventHandler(object sender, GetUsersByRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegistrationInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegistrationInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertPropertyCompletedEventHandler(object sender, InsertPropertyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591