//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Irmac.MailingCycle.BLLServiceLoader.Order {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderServiceSoap", Namespace="http://localhost:3555/BLLService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseInfo))]
    public partial class OrderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInventoryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSearchOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSearchInventoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrderService() {
            this.Url = global::Irmac.MailingCycle.BLLServiceLoader.Properties.Settings.Default.Irmac_MailingCycle_BLLServiceLoader_Order_OrderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertCompletedEventHandler InsertCompleted;
        
        /// <remarks/>
        public event GetCreditCardCompletedEventHandler GetCreditCardCompleted;
        
        /// <remarks/>
        public event GetListCompletedEventHandler GetListCompleted;
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event GetInventoryListCompletedEventHandler GetInventoryListCompleted;
        
        /// <remarks/>
        public event GetSearchOrdersCompletedEventHandler GetSearchOrdersCompleted;
        
        /// <remarks/>
        public event GetSearchInventoryCompletedEventHandler GetSearchInventoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/Insert", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Insert(int userId, OrderInfo order, int ownerId) {
            object[] results = this.Invoke("Insert", new object[] {
                        userId,
                        order,
                        ownerId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertAsync(int userId, OrderInfo order, int ownerId) {
            this.InsertAsync(userId, order, ownerId, null);
        }
        
        /// <remarks/>
        public void InsertAsync(int userId, OrderInfo order, int ownerId, object userState) {
            if ((this.InsertOperationCompleted == null)) {
                this.InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOperationCompleted);
            }
            this.InvokeAsync("Insert", new object[] {
                        userId,
                        order,
                        ownerId}, this.InsertOperationCompleted, userState);
        }
        
        private void OnInsertOperationCompleted(object arg) {
            if ((this.InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCompleted(this, new InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/GetCreditCard", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditCardInfo GetCreditCard(int userId) {
            object[] results = this.Invoke("GetCreditCard", new object[] {
                        userId});
            return ((CreditCardInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditCardAsync(int userId) {
            this.GetCreditCardAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetCreditCardAsync(int userId, object userState) {
            if ((this.GetCreditCardOperationCompleted == null)) {
                this.GetCreditCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditCardOperationCompleted);
            }
            this.InvokeAsync("GetCreditCard", new object[] {
                        userId}, this.GetCreditCardOperationCompleted, userState);
        }
        
        private void OnGetCreditCardOperationCompleted(object arg) {
            if ((this.GetCreditCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditCardCompleted(this, new GetCreditCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/GetList", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInfo[] GetList(int userId) {
            object[] results = this.Invoke("GetList", new object[] {
                        userId});
            return ((OrderInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListAsync(int userId) {
            this.GetListAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetListAsync(int userId, object userState) {
            if ((this.GetListOperationCompleted == null)) {
                this.GetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOperationCompleted);
            }
            this.InvokeAsync("GetList", new object[] {
                        userId}, this.GetListOperationCompleted, userState);
        }
        
        private void OnGetListOperationCompleted(object arg) {
            if ((this.GetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListCompleted(this, new GetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/GetItems", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderItemInfo[] GetItems(int orderId) {
            object[] results = this.Invoke("GetItems", new object[] {
                        orderId});
            return ((OrderItemInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(int orderId) {
            this.GetItemsAsync(orderId, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(int orderId, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        orderId}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/GetInventoryList", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InventoryInfo[] GetInventoryList(int userId) {
            object[] results = this.Invoke("GetInventoryList", new object[] {
                        userId});
            return ((InventoryInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInventoryListAsync(int userId) {
            this.GetInventoryListAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetInventoryListAsync(int userId, object userState) {
            if ((this.GetInventoryListOperationCompleted == null)) {
                this.GetInventoryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInventoryListOperationCompleted);
            }
            this.InvokeAsync("GetInventoryList", new object[] {
                        userId}, this.GetInventoryListOperationCompleted, userState);
        }
        
        private void OnGetInventoryListOperationCompleted(object arg) {
            if ((this.GetInventoryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInventoryListCompleted(this, new GetInventoryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/GetSearchOrders", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInfo[] GetSearchOrders(int userId, int orderId, int cardType, System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("GetSearchOrders", new object[] {
                        userId,
                        orderId,
                        cardType,
                        startDate,
                        endDate});
            return ((OrderInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSearchOrdersAsync(int userId, int orderId, int cardType, System.DateTime startDate, System.DateTime endDate) {
            this.GetSearchOrdersAsync(userId, orderId, cardType, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetSearchOrdersAsync(int userId, int orderId, int cardType, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.GetSearchOrdersOperationCompleted == null)) {
                this.GetSearchOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSearchOrdersOperationCompleted);
            }
            this.InvokeAsync("GetSearchOrders", new object[] {
                        userId,
                        orderId,
                        cardType,
                        startDate,
                        endDate}, this.GetSearchOrdersOperationCompleted, userState);
        }
        
        private void OnGetSearchOrdersOperationCompleted(object arg) {
            if ((this.GetSearchOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSearchOrdersCompleted(this, new GetSearchOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3555/BLLService/GetSearchInventory", RequestNamespace="http://localhost:3555/BLLService/", ResponseNamespace="http://localhost:3555/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InventoryItemReportInfo[] GetSearchInventory(int userId, System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("GetSearchInventory", new object[] {
                        userId,
                        startDate,
                        endDate});
            return ((InventoryItemReportInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSearchInventoryAsync(int userId, System.DateTime startDate, System.DateTime endDate) {
            this.GetSearchInventoryAsync(userId, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetSearchInventoryAsync(int userId, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.GetSearchInventoryOperationCompleted == null)) {
                this.GetSearchInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSearchInventoryOperationCompleted);
            }
            this.InvokeAsync("GetSearchInventory", new object[] {
                        userId,
                        startDate,
                        endDate}, this.GetSearchInventoryOperationCompleted, userState);
        }
        
        private void OnGetSearchInventoryOperationCompleted(object arg) {
            if ((this.GetSearchInventoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSearchInventoryCompleted(this, new GetSearchInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class OrderInfo : BaseInfo {
        
        private decimal refundAmountField;
        
        private bool transactionStatusField;
        
        private int orderIdField;
        
        private object numberField;
        
        private OrderType typeField;
        
        private System.DateTime dateField;
        
        private decimal amountField;
        
        private int transactionCodeField;
        
        private string transactionMessageField;
        
        private CreditCardInfo creditCardField;
        
        private OrderItemInfo[] itemsField;
        
        private string userNameField;
        
        /// <remarks/>
        public decimal RefundAmount {
            get {
                return this.refundAmountField;
            }
            set {
                this.refundAmountField = value;
            }
        }
        
        /// <remarks/>
        public bool TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public int OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public object Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public OrderType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionMessage {
            get {
                return this.transactionMessageField;
            }
            set {
                this.transactionMessageField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardInfo CreditCard {
            get {
                return this.creditCardField;
            }
            set {
                this.creditCardField = value;
            }
        }
        
        /// <remarks/>
        public OrderItemInfo[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LookupInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryItemReportInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryItemInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderItemInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public abstract partial class BaseInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class StateInfo : BaseInfo {
        
        private int stateIdField;
        
        private string nameField;
        
        /// <remarks/>
        public int StateId {
            get {
                return this.stateIdField;
            }
            set {
                this.stateIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class CountryInfo : BaseInfo {
        
        private int countryIdField;
        
        private string nameField;
        
        private bool isDefaultField;
        
        /// <remarks/>
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class AddressInfo : BaseInfo {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private CountryInfo countryField;
        
        private StateInfo stateField;
        
        private string zipField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string faxField;
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public CountryInfo Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public StateInfo State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class LookupInfo : BaseInfo {
        
        private int lookupIdField;
        
        private string nameField;
        
        /// <remarks/>
        public int LookupId {
            get {
                return this.lookupIdField;
            }
            set {
                this.lookupIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class CreditCardInfo : BaseInfo {
        
        private LookupInfo typeField;
        
        private string numberField;
        
        private string cvvNumberField;
        
        private string holderNameField;
        
        private int expirationMonthField;
        
        private int expirationYearField;
        
        private AddressInfo addressField;
        
        /// <remarks/>
        public LookupInfo Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string CvvNumber {
            get {
                return this.cvvNumberField;
            }
            set {
                this.cvvNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HolderName {
            get {
                return this.holderNameField;
            }
            set {
                this.holderNameField = value;
            }
        }
        
        /// <remarks/>
        public int ExpirationMonth {
            get {
                return this.expirationMonthField;
            }
            set {
                this.expirationMonthField = value;
            }
        }
        
        /// <remarks/>
        public int ExpirationYear {
            get {
                return this.expirationYearField;
            }
            set {
                this.expirationYearField = value;
            }
        }
        
        /// <remarks/>
        public AddressInfo Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class InventoryItemReportInfo : BaseInfo {
        
        private int sumQuantityBRField;
        
        private int sumQuantityPKField;
        
        private int sumQuantityENField;
        
        private int quantityENField;
        
        private int quantityBRField;
        
        private int quantityPKField;
        
        private System.DateTime transactionDateField;
        
        private TransactionType orderTransactionTypeField;
        
        /// <remarks/>
        public int SumQuantityBR {
            get {
                return this.sumQuantityBRField;
            }
            set {
                this.sumQuantityBRField = value;
            }
        }
        
        /// <remarks/>
        public int SumQuantityPK {
            get {
                return this.sumQuantityPKField;
            }
            set {
                this.sumQuantityPKField = value;
            }
        }
        
        /// <remarks/>
        public int SumQuantityEN {
            get {
                return this.sumQuantityENField;
            }
            set {
                this.sumQuantityENField = value;
            }
        }
        
        /// <remarks/>
        public int QuantityEN {
            get {
                return this.quantityENField;
            }
            set {
                this.quantityENField = value;
            }
        }
        
        /// <remarks/>
        public int QuantityBR {
            get {
                return this.quantityBRField;
            }
            set {
                this.quantityBRField = value;
            }
        }
        
        /// <remarks/>
        public int QuantityPK {
            get {
                return this.quantityPKField;
            }
            set {
                this.quantityPKField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public TransactionType OrderTransactionType {
            get {
                return this.orderTransactionTypeField;
            }
            set {
                this.orderTransactionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public enum TransactionType {
        
        /// <remarks/>
        Purchased,
        
        /// <remarks/>
        Used,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class InventoryInfo : BaseInfo {
        
        private InventoryItemInfo[] inventoryItemsField;
        
        private int quantityOnHandField;
        
        private ProductCategory categoryTypeField;
        
        /// <remarks/>
        public InventoryItemInfo[] InventoryItems {
            get {
                return this.inventoryItemsField;
            }
            set {
                this.inventoryItemsField = value;
            }
        }
        
        /// <remarks/>
        public int QuantityOnHand {
            get {
                return this.quantityOnHandField;
            }
            set {
                this.quantityOnHandField = value;
            }
        }
        
        /// <remarks/>
        public ProductCategory CategoryType {
            get {
                return this.categoryTypeField;
            }
            set {
                this.categoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class InventoryItemInfo : BaseInfo {
        
        private string remarksField;
        
        private int quantityField;
        
        private System.DateTime transactionDateField;
        
        private TransactionType orderTransactionTypeField;
        
        private int transactionIdField;
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public TransactionType OrderTransactionType {
            get {
                return this.orderTransactionTypeField;
            }
            set {
                this.orderTransactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public enum ProductCategory {
        
        /// <remarks/>
        PowerKard,
        
        /// <remarks/>
        Brochure,
        
        /// <remarks/>
        Envelope,
        
        /// <remarks/>
        House_Fliers,
        
        /// <remarks/>
        Generic_Product,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public partial class OrderItemInfo : BaseInfo {
        
        private string itemIdField;
        
        private string titleField;
        
        private OrderItemType typeField;
        
        private int quantityField;
        
        private decimal rateField;
        
        /// <remarks/>
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public OrderItemType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public enum OrderItemType {
        
        /// <remarks/>
        Product,
        
        /// <remarks/>
        ProductPackage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:3555/BLLService/")]
    public enum OrderType {
        
        /// <remarks/>
        MembershipFee,
        
        /// <remarks/>
        MailingFee,
        
        /// <remarks/>
        PrePrintedCards,
        
        /// <remarks/>
        ShoppingCart,
        
        /// <remarks/>
        Event,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertCompletedEventHandler(object sender, InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCreditCardCompletedEventHandler(object sender, GetCreditCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditCardInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditCardInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListCompletedEventHandler(object sender, GetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderItemInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderItemInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetInventoryListCompletedEventHandler(object sender, GetInventoryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInventoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInventoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSearchOrdersCompletedEventHandler(object sender, GetSearchOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSearchOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSearchOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSearchInventoryCompletedEventHandler(object sender, GetSearchInventoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSearchInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSearchInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryItemReportInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryItemReportInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591