//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Irmac.MailingCycle.BLLServiceLoader.Product {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductServiceSoap", Namespace="http://mc.mkbedev.com/BLLService/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseInfo))]
    public partial class ProductService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProductDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInventoryTotalCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductService() {
            this.Url = "http://mc1.mkbedev.com/BLLService/ProductService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductItemsCompletedEventHandler GetProductItemsCompleted;
        
        /// <remarks/>
        public event InsertProductCompletedEventHandler InsertProductCompleted;
        
        /// <remarks/>
        public event GetProductsCompletedEventHandler GetProductsCompleted;
        
        /// <remarks/>
        public event GetProductDetailsCompletedEventHandler GetProductDetailsCompleted;
        
        /// <remarks/>
        public event UpdateProductDetailsCompletedEventHandler UpdateProductDetailsCompleted;
        
        /// <remarks/>
        public event DeleteProductCompletedEventHandler DeleteProductCompleted;
        
        /// <remarks/>
        public event GetInventoryTotalCountCompletedEventHandler GetInventoryTotalCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetProductItems", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductItemInfo[] GetProductItems() {
            object[] results = this.Invoke("GetProductItems", new object[0]);
            return ((ProductItemInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductItemsAsync() {
            this.GetProductItemsAsync(null);
        }
        
        /// <remarks/>
        public void GetProductItemsAsync(object userState) {
            if ((this.GetProductItemsOperationCompleted == null)) {
                this.GetProductItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductItemsOperationCompleted);
            }
            this.InvokeAsync("GetProductItems", new object[0], this.GetProductItemsOperationCompleted, userState);
        }
        
        private void OnGetProductItemsOperationCompleted(object arg) {
            if ((this.GetProductItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductItemsCompleted(this, new GetProductItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/InsertProduct", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertProduct(ProductInfo productInfo) {
            object[] results = this.Invoke("InsertProduct", new object[] {
                        productInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertProductAsync(ProductInfo productInfo) {
            this.InsertProductAsync(productInfo, null);
        }
        
        /// <remarks/>
        public void InsertProductAsync(ProductInfo productInfo, object userState) {
            if ((this.InsertProductOperationCompleted == null)) {
                this.InsertProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertProductOperationCompleted);
            }
            this.InvokeAsync("InsertProduct", new object[] {
                        productInfo}, this.InsertProductOperationCompleted, userState);
        }
        
        private void OnInsertProductOperationCompleted(object arg) {
            if ((this.InsertProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertProductCompleted(this, new InsertProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetProducts", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] GetProducts(int productTypeId, int agentUserId) {
            object[] results = this.Invoke("GetProducts", new object[] {
                        productTypeId,
                        agentUserId});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsAsync(int productTypeId, int agentUserId) {
            this.GetProductsAsync(productTypeId, agentUserId, null);
        }
        
        /// <remarks/>
        public void GetProductsAsync(int productTypeId, int agentUserId, object userState) {
            if ((this.GetProductsOperationCompleted == null)) {
                this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
            }
            this.InvokeAsync("GetProducts", new object[] {
                        productTypeId,
                        agentUserId}, this.GetProductsOperationCompleted, userState);
        }
        
        private void OnGetProductsOperationCompleted(object arg) {
            if ((this.GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetProductDetails", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo GetProductDetails(string productId) {
            object[] results = this.Invoke("GetProductDetails", new object[] {
                        productId});
            return ((ProductInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductDetailsAsync(string productId) {
            this.GetProductDetailsAsync(productId, null);
        }
        
        /// <remarks/>
        public void GetProductDetailsAsync(string productId, object userState) {
            if ((this.GetProductDetailsOperationCompleted == null)) {
                this.GetProductDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductDetailsOperationCompleted);
            }
            this.InvokeAsync("GetProductDetails", new object[] {
                        productId}, this.GetProductDetailsOperationCompleted, userState);
        }
        
        private void OnGetProductDetailsOperationCompleted(object arg) {
            if ((this.GetProductDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductDetailsCompleted(this, new GetProductDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/UpdateProductDetails", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateProductDetails(ProductInfo productInfo) {
            object[] results = this.Invoke("UpdateProductDetails", new object[] {
                        productInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProductDetailsAsync(ProductInfo productInfo) {
            this.UpdateProductDetailsAsync(productInfo, null);
        }
        
        /// <remarks/>
        public void UpdateProductDetailsAsync(ProductInfo productInfo, object userState) {
            if ((this.UpdateProductDetailsOperationCompleted == null)) {
                this.UpdateProductDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProductDetailsOperationCompleted);
            }
            this.InvokeAsync("UpdateProductDetails", new object[] {
                        productInfo}, this.UpdateProductDetailsOperationCompleted, userState);
        }
        
        private void OnUpdateProductDetailsOperationCompleted(object arg) {
            if ((this.UpdateProductDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProductDetailsCompleted(this, new UpdateProductDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/DeleteProduct", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteProduct(string productId, int userId) {
            object[] results = this.Invoke("DeleteProduct", new object[] {
                        productId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProductAsync(string productId, int userId) {
            this.DeleteProductAsync(productId, userId, null);
        }
        
        /// <remarks/>
        public void DeleteProductAsync(string productId, int userId, object userState) {
            if ((this.DeleteProductOperationCompleted == null)) {
                this.DeleteProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProductOperationCompleted);
            }
            this.InvokeAsync("DeleteProduct", new object[] {
                        productId,
                        userId}, this.DeleteProductOperationCompleted, userState);
        }
        
        private void OnDeleteProductOperationCompleted(object arg) {
            if ((this.DeleteProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProductCompleted(this, new DeleteProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mc.mkbedev.com/BLLService/GetInventoryTotalCount", RequestNamespace="http://mc.mkbedev.com/BLLService/", ResponseNamespace="http://mc.mkbedev.com/BLLService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductItemInfo[] GetInventoryTotalCount(int agentUserId) {
            object[] results = this.Invoke("GetInventoryTotalCount", new object[] {
                        agentUserId});
            return ((ProductItemInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInventoryTotalCountAsync(int agentUserId) {
            this.GetInventoryTotalCountAsync(agentUserId, null);
        }
        
        /// <remarks/>
        public void GetInventoryTotalCountAsync(int agentUserId, object userState) {
            if ((this.GetInventoryTotalCountOperationCompleted == null)) {
                this.GetInventoryTotalCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInventoryTotalCountOperationCompleted);
            }
            this.InvokeAsync("GetInventoryTotalCount", new object[] {
                        agentUserId}, this.GetInventoryTotalCountOperationCompleted, userState);
        }
        
        private void OnGetInventoryTotalCountOperationCompleted(object arg) {
            if ((this.GetInventoryTotalCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInventoryTotalCountCompleted(this, new GetInventoryTotalCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class ProductItemInfo {
        
        private int productTypeIdField;
        
        private int agentUserIdField;
        
        private decimal priceField;
        
        private int quantityField;
        
        private string[] sizeField;
        
        private bool isCustomSizeField;
        
        private string productTypeField;
        
        /// <remarks/>
        public int ProductTypeId {
            get {
                return this.productTypeIdField;
            }
            set {
                this.productTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public int AgentUserId {
            get {
                return this.agentUserIdField;
            }
            set {
                this.agentUserIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string[] Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCustomSize {
            get {
                return this.isCustomSizeField;
            }
            set {
                this.isCustomSizeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public abstract partial class BaseInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public partial class ProductInfo : BaseInfo {
        
        private string briefDescWithQuantityField;
        
        private decimal totalPriceField;
        
        private int ownerIdField;
        
        private ProductItemInfo[] productItemsField;
        
        private ProductStatus productStatusField;
        
        private string extDescField;
        
        private string briefDescField;
        
        private string productIdField;
        
        private ProductCatalogType productCatalogField;
        
        /// <remarks/>
        public string BriefDescWithQuantity {
            get {
                return this.briefDescWithQuantityField;
            }
            set {
                this.briefDescWithQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        public int OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        public ProductItemInfo[] ProductItems {
            get {
                return this.productItemsField;
            }
            set {
                this.productItemsField = value;
            }
        }
        
        /// <remarks/>
        public ProductStatus ProductStatus {
            get {
                return this.productStatusField;
            }
            set {
                this.productStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ExtDesc {
            get {
                return this.extDescField;
            }
            set {
                this.extDescField = value;
            }
        }
        
        /// <remarks/>
        public string BriefDesc {
            get {
                return this.briefDescField;
            }
            set {
                this.briefDescField = value;
            }
        }
        
        /// <remarks/>
        public string ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public ProductCatalogType ProductCatalog {
            get {
                return this.productCatalogField;
            }
            set {
                this.productCatalogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public enum ProductStatus {
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        OnHold,
        
        /// <remarks/>
        Obsolete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mc.mkbedev.com/BLLService/")]
    public enum ProductCatalogType {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Custom,
        
        /// <remarks/>
        Generic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductItemsCompletedEventHandler(object sender, GetProductItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductItemInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductItemInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertProductCompletedEventHandler(object sender, InsertProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductDetailsCompletedEventHandler(object sender, GetProductDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateProductDetailsCompletedEventHandler(object sender, UpdateProductDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProductDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProductDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteProductCompletedEventHandler(object sender, DeleteProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInventoryTotalCountCompletedEventHandler(object sender, GetInventoryTotalCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInventoryTotalCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInventoryTotalCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductItemInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductItemInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591